run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
      path: stdout

linters-settings:
  govet:
    enable:
      - shadow
  gocyclo:
    min-complexity: 35
  goconst:
    min-len: 3
    min-occurrences: 3
  depguard:
    rules:
      main:
        allow:
          - $all
          - $gostd
          - chess-game
        deny: []
  gosec:
    excludes:
      - G115 # Integer overflow conversion - acceptable for our use case

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gocyclo
    - goconst
    - gofmt
    - goimports
    - revive
    - stylecheck
    - gosec
    - depguard
  disable: []

issues:
  exclude-files:
    - ".*_test.go"
  exclude-dirs:
    - vendor
    - bin
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
    - linters:
        - stylecheck
      text: "ST1000"
      path: "main.go"

  exclude:
    - abcdef

  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

severity:
  default-severity: error
  case-sensitive: false 